create database atmstimulator;
show databases;
use atmstimulator;
create table signup(formno varchar(20),name varchar(20),father_name varchar(20),dob varchar(20),gender varchar(20),email varchar(30),marital_status varchar(20),city varchar(20),address varchar(40),pincode varchar(20),state varchar(25));
show tables;
select * from signup;
create table signup2(formno varchar(20),religion varchar(20),category varchar(20),income varchar(20),education varchar(20),occupation varchar(30),pan varchar(20),aadhar varchar(20),seniorcitizen varchar(40),existingaccount varchar(20));
select * from signup2;
create table signup3(formno varchar(20),atype varchar(20), cardno varchar(20),pin varchar(20),facility varchar(100));
create table login(formno varchar(20),cardno varchar(20),pin varchar(100));
select * from signup3;
drop table login;
create table login(formno varchar(20),cardnumber varchar(20),pin varchar(100));
select * from login;
drop table login;
create table login(formno varchar(20),cardnumber varchar(20),pin varchar(100));
create table bank(pin varchar(10), date varchar(20), type varchar(20),amount varchar(20));